#!/bin/bash
# Audit Trail Hooks
# Captures agent delegations, completions, and failures to session logs
#
# Claude Code passes JSON on stdin with these fields:
# - hook_event_name: SubagentStart, SubagentStop, PostToolUseFailure, etc.
# - session_id: Current session ID
# - transcript_path: Path to full transcript JSONL
# - agent_type: For subagent events
# - agent_id: For subagent events
# - tool_name: For tool events
# - error: For failure events

# Configuration
AUDIT_DIR=".claude/audit/sessions"
DATE=$(date +%Y-%m-%d)
LOG_FILE="$AUDIT_DIR/$DATE.md"
TIMESTAMP=$(date +%H:%M:%S)
FULL_TIMESTAMP=$(date -Iseconds 2>/dev/null || date +%Y-%m-%dT%H:%M:%S)

# Ensure audit directory exists
mkdir -p "$AUDIT_DIR"

# Initialize log file if it doesn't exist
if [ ! -f "$LOG_FILE" ]; then
    cat > "$LOG_FILE" << EOF
# Session Log: $DATE

> Auto-generated by audit-hooks.sh

EOF
fi

# Read JSON from stdin
INPUT=$(cat)

# Debug: Log raw JSON to help diagnose field extraction issues
DEBUG_LOG="$AUDIT_DIR/debug.log"
echo "=== $(date -Iseconds 2>/dev/null || date) ===" >> "$DEBUG_LOG"
echo "$INPUT" >> "$DEBUG_LOG"
echo "" >> "$DEBUG_LOG"

# Function to extract JSON field using Node.js (available in Node projects)
# Falls back to grep patterns if Node isn't available
extract_field() {
    local field="$1"
    local default="$2"

    # Try Node.js first (most reliable, available in Node projects)
    if command -v node &> /dev/null; then
        result=$(echo "$INPUT" | node -e "
            let data = '';
            process.stdin.on('data', chunk => data += chunk);
            process.stdin.on('end', () => {
                try {
                    const obj = JSON.parse(data);
                    // Handle both missing AND empty string values
                    const val = obj['$field'];
                    console.log((val !== undefined && val !== null && val !== '') ? val : '$default');
                } catch(e) {
                    console.log('$default');
                }
            });
        " 2>/dev/null)
        echo "$result"
        return
    fi

    # Try jq if available
    if command -v jq &> /dev/null; then
        echo "$INPUT" | jq -r ".$field // \"$default\"" 2>/dev/null
        return
    fi

    # Fallback: basic grep pattern (less reliable but works without dependencies)
    result=$(echo "$INPUT" | grep -oP "\"$field\":\s*\"[^\"]*\"" | head -1 | sed 's/.*":"\([^"]*\)".*/\1/')
    if [ -n "$result" ]; then
        echo "$result"
    else
        echo "$default"
    fi
}

# Extract common fields from JSON
EVENT_TYPE=$(extract_field "hook_event_name" "unknown")
SESSION_ID=$(extract_field "session_id" "unknown")

# Parse based on event type
case "$EVENT_TYPE" in
    "SubagentStart")
        AGENT_TYPE=$(extract_field "agent_type" "skill")
        AGENT_ID=$(extract_field "agent_id" "unknown")

        cat >> "$LOG_FILE" << EOF

### $TIMESTAMP - Agent Delegated: $AGENT_TYPE

| Field | Value |
|-------|-------|
| Timestamp | $FULL_TIMESTAMP |
| Agent Type | $AGENT_TYPE |
| Agent ID | $AGENT_ID |
| Session | $SESSION_ID |
| Status | In Progress |

EOF
        ;;

    "SubagentStop")
        AGENT_TYPE=$(extract_field "agent_type" "skill")
        AGENT_ID=$(extract_field "agent_id" "unknown")
        AGENT_TRANSCRIPT=$(extract_field "agent_transcript_path" "")

        cat >> "$LOG_FILE" << EOF

### $TIMESTAMP - Agent Completed: $AGENT_TYPE

| Field | Value |
|-------|-------|
| Timestamp | $FULL_TIMESTAMP |
| Agent Type | $AGENT_TYPE |
| Agent ID | $AGENT_ID |
| Transcript | $AGENT_TRANSCRIPT |
| Status | Completed |

EOF
        ;;

    "PostToolUseFailure")
        TOOL_NAME=$(extract_field "tool_name" "unknown")
        ERROR_MSG=$(extract_field "error" "unknown error")
        # Truncate and sanitize error message
        ERROR_MSG=$(echo "$ERROR_MSG" | head -c 500 | tr '\n' ' ' | sed 's/|/\\|/g')

        cat >> "$LOG_FILE" << EOF

### $TIMESTAMP - Tool Failed: $TOOL_NAME

| Field | Value |
|-------|-------|
| Timestamp | $FULL_TIMESTAMP |
| Tool | $TOOL_NAME |
| Error | $ERROR_MSG |
| Session | $SESSION_ID |

EOF
        ;;

    "SessionStart")
        SOURCE=$(extract_field "source" "unknown")
        MODEL=$(extract_field "model" "unknown")

        cat >> "$LOG_FILE" << EOF

---

## Session Started: $FULL_TIMESTAMP

| Field | Value |
|-------|-------|
| Source | $SOURCE |
| Model | $MODEL |
| Session ID | $SESSION_ID |

EOF
        ;;

    "SessionEnd")
        REASON=$(extract_field "reason" "unknown")

        cat >> "$LOG_FILE" << EOF

## Session Ended: $FULL_TIMESTAMP

| Field | Value |
|-------|-------|
| Reason | $REASON |
| Session ID | $SESSION_ID |

---

EOF
        ;;

    "unknown"|"")
        # No event type - log for debugging
        echo "### $TIMESTAMP - Hook fired (no event type parsed)" >> "$LOG_FILE"
        ;;

    *)
        # Log other events
        echo "### $TIMESTAMP - Event: $EVENT_TYPE (session: $SESSION_ID)" >> "$LOG_FILE"
        ;;
esac

# Always exit successfully - audit should never block operations
exit 0
