#!/usr/bin/env node
// Audit Trail Hooks (Node.js - cross-platform)
// Captures agent delegations, completions, and failures to session logs
//
// Uses Node.js instead of bash for reliable Windows + macOS + Linux support.

import { mkdirSync, existsSync, writeFileSync, appendFileSync } from 'fs';
import { join } from 'path';

const AUDIT_DIR = '.claude/audit/sessions';

function getDate() {
  return new Date().toISOString().split('T')[0];
}

function getTime() {
  return new Date().toTimeString().split(' ')[0];
}

function getFullTimestamp() {
  return new Date().toISOString();
}

function ensureDir(dir) {
  mkdirSync(dir, { recursive: true });
}

function initLogFile(logFile, date) {
  if (!existsSync(logFile)) {
    writeFileSync(logFile, `# Session Log: ${date}\n\n> Auto-generated by audit-hooks.mjs\n\n`);
  }
}

function appendLog(logFile, content) {
  appendFileSync(logFile, content);
}

// Read all stdin
const chunks = [];
process.stdin.on('data', chunk => chunks.push(chunk));
process.stdin.on('end', () => {
  try {
    const date = getDate();
    const timestamp = getTime();
    const fullTimestamp = getFullTimestamp();
    const logFile = join(AUDIT_DIR, `${date}.md`);

    ensureDir(AUDIT_DIR);
    initLogFile(logFile, date);

    // Debug log
    const rawInput = Buffer.concat(chunks).toString();
    const debugLog = join(AUDIT_DIR, 'debug.log');
    appendFileSync(debugLog, `=== ${fullTimestamp} ===\n${rawInput}\n\n`);

    const input = JSON.parse(rawInput);
    const eventType = input.hook_event_name || 'unknown';
    const sessionId = input.session_id || 'unknown';

    switch (eventType) {
      case 'SubagentStart': {
        const agentType = input.agent_type || 'skill';
        const agentId = input.agent_id || 'unknown';
        appendLog(logFile, `
### ${timestamp} - Agent Delegated: ${agentType}

| Field | Value |
|-------|-------|
| Timestamp | ${fullTimestamp} |
| Agent Type | ${agentType} |
| Agent ID | ${agentId} |
| Session | ${sessionId} |
| Status | In Progress |

`);
        break;
      }

      case 'SubagentStop': {
        const agentType = input.agent_type || 'skill';
        const agentId = input.agent_id || 'unknown';
        const transcript = input.agent_transcript_path || '';
        appendLog(logFile, `
### ${timestamp} - Agent Completed: ${agentType}

| Field | Value |
|-------|-------|
| Timestamp | ${fullTimestamp} |
| Agent Type | ${agentType} |
| Agent ID | ${agentId} |
| Transcript | ${transcript} |
| Status | Completed |

`);
        break;
      }

      case 'PostToolUseFailure': {
        const toolName = input.tool_name || 'unknown';
        let errorMsg = (input.error || 'unknown error').substring(0, 500).replace(/\n/g, ' ').replace(/\|/g, '\\|');
        appendLog(logFile, `
### ${timestamp} - Tool Failed: ${toolName}

| Field | Value |
|-------|-------|
| Timestamp | ${fullTimestamp} |
| Tool | ${toolName} |
| Error | ${errorMsg} |
| Session | ${sessionId} |

`);
        break;
      }

      case 'SessionStart': {
        const source = input.source || 'unknown';
        const model = input.model || 'unknown';
        appendLog(logFile, `
---

## Session Started: ${fullTimestamp}

| Field | Value |
|-------|-------|
| Source | ${source} |
| Model | ${model} |
| Session ID | ${sessionId} |

`);
        break;
      }

      case 'SessionEnd': {
        const reason = input.reason || 'unknown';
        appendLog(logFile, `
## Session Ended: ${fullTimestamp}

| Field | Value |
|-------|-------|
| Reason | ${reason} |
| Session ID | ${sessionId} |

---

`);
        break;
      }

      case 'unknown':
      case '':
        appendLog(logFile, `### ${timestamp} - Hook fired (no event type parsed)\n`);
        break;

      default:
        appendLog(logFile, `### ${timestamp} - Event: ${eventType} (session: ${sessionId})\n`);
        break;
    }
  } catch {
    // Audit should never block operations
  }

  // Always exit successfully
  process.exit(0);
});
